# store/items.py

SHOP_ITEMS = [
    # --- Permanent Roles ---
    {
        "item_id": "not_cute", 
        "name": "Not Cute Role", 
        "description": "show everyone how ugly you are",
        "image_url": "", 
        "category": "Roles", 
        "price": 2500, 
        "quantity": -1, 
        "role_id": 1500641032528728237, 
        "rotation_type": "permanent", 
        "is_active": True
    },
    {
        "item_id": "chill_vibes", 
        "name": "Chill Vibes", 
        "description": "For those who just want to kick back and relax",
        "image_url": "",
        "category": "Roles", 
        "price": 2500, 
        "quantity": -1, 
        "role_id": 1500647822352187498, 
        "rotation_type": "permanent", 
        "is_active": True
    },
    {
        "item_id": "high_roller", 
        "name": "High Roller", 
        "description": "Flex your massive wealth on the peasants",
        "image_url": "",
        "category": "Roles", 
        "price": 10000, 
        "quantity": -1, 
        "role_id": 1500648243124502588, 
        "rotation_type": "permanent", 
        "is_active": True
    },
    {
        "item_id": "sugar_rush", 
        "name": "Sugar Rush", 
        "description": "A sweet and vibrant burst of energy",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1501376521988739153, 
        "rotation_type": "permanent", 
        "is_active": True
    },
    {
        "item_id": "gummy_shark", 
        "name": "Gummy Shark", 
        "description": "Bite-sized oceanic chaos in neon blue and pink",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1501376810829615184, 
        "rotation_type": "permanent", 
        "is_active": True
    },
    {
        "item_id": "candy_apple", 
        "name": "Candy Apple", 
        "description": "High-gloss, electric sweetness",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1501378054058938418, 
        "rotation_type": "permanent", 
        "is_active": True
    },
    {
        "item_id": "sunbeam", 
        "name": "Sunbeam", 
        "description": "Radiant high noon yellow and deep sun gold",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1501572669664002068, 
        "rotation_type": "permanent", 
        "is_active": True
    },
    {
        "item_id": "mango_sorbet", 
        "name": "Mango Sorbet", 
        "description": "Sweet honey yellow and mango orange",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1501572861330980874, 
        "rotation_type": "permanent", 
        "is_active": True
    },
    {
        "item_id": "midnight_bonfire", 
        "name": "Midnight Bonfire", 
        "description": "Starry midnight blue and cool evening steel",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1501573196288098334, 
        "rotation_type": "permanent", 
        "is_active": True
    },
    
    # --- Daily Roles ---
    {
        "item_id": "himbo", 
        "name": "Himbo", 
        "description": "Pure of heart, broad of chest, empty of head",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1500658423040311296, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "pixie_dust", 
        "name": "Pixie Dust", 
        "description": "A shimmering trail of magic and mystery",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1501377253685198869, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "mint_chip", 
        "name": "Mint Chip", 
        "description": "Cool, refreshing, and sweet",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1501377389329121320, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "spring", 
        "name": "Spring", 
        "description": "A fresh start and blooming flowers",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1500901506650607817, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "summer", 
        "name": "Summer", 
        "description": "Sun, sand, and good vibes",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1500901616746758144, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "winter", 
        "name": "Winter", 
        "description": "Cozy nights and falling snow",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1500901720996188220, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "fall", 
        "name": "Fall", 
        "description": "Crisp air and autumn leaves",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1500901941331361959, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "watermelon", 
        "name": "Watermelon", 
        "description": "Vibrant melon pink and sweet lime green",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1501571438404960386, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "wave_runner", 
        "name": "Wave Runner", 
        "description": "Deep ocean blue crashing into a seafoam crest",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1501571561214181447, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "poolside_cabana", 
        "name": "Poolside Cabana", 
        "description": "Tropical magenta and bright Miami cyan",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1501571685193613392, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "bomb_pop", 
        "name": "Bomb Pop", 
        "description": "A classic summer treat of cherry red and icy blue",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1501572011531698287, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "retro_waves", 
        "name": "Retro Waves", 
        "description": "A high-speed chase through an 80s neon grid",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1503461664379633694, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "dragonfruit", 
        "name": "Dragonfruit", 
        "description": "Vibrant, exotic, and visually striking",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1503462249455685652, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "hotsauce", 
        "name": "Hot Sauce", 
        "description": "Bold, spicy, and guaranteed to leave a lasting impression",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1503461774169608432, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "Lavendar", 
        "name": "Lavendar", 
        "description": "Calm and floral. The peak of soft-core aesthetic",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1503462380024107158, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "afterparty", 
        "name": "After Party", 
        "description": "The sun is coming up but the music hasn't stopped",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1503462713614008400, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "absinthe", 
        "name": "Absinthe", 
        "description": "Hallucinogenic levels of chaotic energy and mystery",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1503462838050754631, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "sex_club", 
        "name": "Sex Club", 
        "description": "Self Explainatory",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1511489605625581568, 
        "rotation_type": "daily", 
        "is_active": False
    },
    {
        "item_id": "raspberry_slush", 
        "name": "Raspberry Slush", 
        "description": "Sapphire syrup mixing with electric cyan",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1501573086565236901, 
        "rotation_type": "daily", 
        "is_active": False
    },

    # --- Permanent Boosters ---
    {
        "item_id": "booster_balance", 
        "name": "2x Leaf Booster", 
        "description": "Double your Leaf earnings for 1d",
        "category": "Boosters", 
        "price": 5000, 
        "quantity": -1,
        "rotation_type": "permanent", 
        "is_active": True,
        "type": "booster",       
        "duration": 3600,        
        "daily_limit": 1         
    },
    {
        "item_id": "booster_xp", 
        "name": "2x XP Booster", 
        "description": "Double your XP gains for 1d",
        "category": "Boosters", 
        "price": 5000, 
        "quantity": -1,
        "rotation_type": "permanent", 
        "is_active": True,
        "type": "booster",       
        "duration": 3600,        
        "daily_limit": 1         
    },
    {
        "item_id": "booster_profile", 
        "name": "Profile Booster (1 day)", 
        "description": "Doubles your dating profile weight for 1d",
        "category": "Boosters", 
        "price": 5000, 
        "quantity": -1,
        "rotation_type": "permanent", 
        "is_active": True,
        "type": "booster",       
        "duration": 86400,       # 24 hours in seconds 
        "daily_limit": 1         
    },

    # --- Weekly Roles ---
    {
        "item_id": "jade_dragon", 
        "name": "Jade Dragon", 
        "description": "Ancient power and gemstone elegance",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1501377780980383835, 
        "rotation_type": "weekly", 
        "is_active": False
    },
    {
        "item_id": "blood_moon", 
        "name": "Blood Moon", 
        "description": "Crimson skies and lunar eclipses",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1501378140990214155, 
        "rotation_type": "weekly", 
        "is_active": False
    },
    {
        "item_id": "caffeine_addict", 
        "name": "Caffeine Addict", 
        "description": "Fueled entirely by espresso and anxiety",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1500649785378734220, 
        "rotation_type": "weekly", 
        "is_active": False
    },
    {
        "item_id": "sleep_deprived", 
        "name": "Sleep Deprived", 
        "description": "What is sleep? Is it edible?",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1500650185225932951, 
        "rotation_type": "weekly", 
        "is_active": False
    },
    {
        "item_id": "stargazer", 
        "name": "Stargazer", 
        "description": "Lost in the cosmos, looking for shooting stars",
        "image_url": "",
        "category": "Roles", 
        "price": 5000, 
        "quantity": -1, 
        "role_id": 1500650864388345936, 
        "rotation_type": "weekly", 
        "is_active": False
    },
    {
        "item_id": "tidepod", 
        "name": "Tide Pod", 
        "description": "They're magically delicious... seriously don't",
        "image_url": "",
        "category": "Roles", 
        "price": 15000, 
        "quantity": -1, 
        "role_id": 1502812038064377946, 
        "rotation_type": "weekly", 
        "is_active": False
    },
    {
        "item_id": "golden_hour", 
        "name": "Golden Hour", 
        "description": "Warm evening gold fading into dusk purple",
        "image_url": "",
        "category": "Roles", 
        "price": 7500, 
        "quantity": -1, 
        "role_id": 1501572099733717024, 
        "rotation_type": "weekly", 
        "is_active": False
    },
    {
        "item_id": "beach_bum", 
        "name": "Beach Bum", 
        "description": "Warm coral and relaxing beach beige",
        "image_url": "",
        "category": "Roles", 
        "price": 7500, 
        "quantity": -1, 
        "role_id": 1501572234781659217, 
        "rotation_type": "weekly", 
        "is_active": False
    },
    {
        "item_id": "spores", 
        "name": "Spores", 
        "description": "It’s growing on you whether you like it or not",
        "image_url": "",
        "category": "Roles", 
        "price": 7500, 
        "quantity": -1, 
        "role_id": 1503463060763971694, 
        "rotation_type": "weekly", 
        "is_active": False
    },
    {
        "item_id": "void", 
        "name": "Void", 
        "description": "Darkness absolute",
        "image_url": "",
        "category": "Roles", 
        "price": 7500, 
        "quantity": -1, 
        "role_id": 1503463516106133585, 
        "rotation_type": "weekly", 
        "is_active": False
    },
    {
        "item_id": "thorns", 
        "name": "Thorns", 
        "description": "Classic elegance with a hidden edge",
        "image_url": "",
        "category": "Roles", 
        "price": 7500, 
        "quantity": -1, 
        "role_id": 1503463648448876584, 
        "rotation_type": "weekly", 
        "is_active": False
    },
    {
        "item_id": "herbert", 
        "name": "Herbert", 
        "description": "Cold, calculating, and slightly villainous",
        "image_url": "",
        "category": "Roles", 
        "price": 7500, 
        "quantity": -1, 
        "role_id": 1503463839755141181, 
        "rotation_type": "weekly", 
        "is_active": False
    },
    {
        "item_id": "golden_puffle", 
        "name": "Golden Puffle", 
        "description": "The ultimate rare companion",
        "image_url": "",
        "category": "Roles", 
        "price": 7500, 
        "quantity": -1, 
        "role_id": 1503464003270348943, 
        "rotation_type": "weekly", 
        "is_active": False
    },
    {
        "item_id": "bubbles", 
        "name": "Bubbles", 
        "description": "Pop Pop..",
        "image_url": "",
        "category": "Roles", 
        "price": 7500, 
        "quantity": -1, 
        "role_id": 1503464681283653782, 
        "rotation_type": "weekly", 
        "is_active": False
    },
    {
        "item_id": "misty", 
        "name": "Misty", 
        "description": "Like a foggy morning on the island",
        "image_url": "",
        "category": "Roles", 
        "price": 7500, 
        "quantity": -1, 
        "role_id": 1503464813198835892, 
        "rotation_type": "weekly", 
        "is_active": False
    },
    {
        "item_id": "sand_dollar", 
        "name": "Sand Dollar", 
        "description": "A crisp gradient of bleached sand and pure white.",
        "image_url": "",
        "category": "Roles", 
        "price": 7500, 
        "quantity": -1, 
        "role_id": 1501572382631137350, 
        "rotation_type": "weekly", 
        "is_active": False
    }
]